[webservers]
ansible-web ansible_host=10.0.1.45

[appservers]
ansible-app ansible_host=10.1.208.105

[dbservers]
ansible-db ansible_host=10.1.92.86

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/ansible-control-server-keypair
ansible_python_interpreter=/usr/bin/python3
